#include "libkinematics/fk.hpp"

#include <gtest/gtest.h>

#include <Eigen/Core>
#include <fstream>
#include <sstream>
#include <vector>

#include "libkinematics/robot.hpp"

using klib::ForwardKinematics;
using klib::Robot;

namespace {
// Each fixture row: q(7) | tool T row-major(16) | link world positions(7*3).
// Reference generated by MuJoCo FK (the kinematics oracle here, standing in for
// KDL; see config yaml header for the placeholder-model note).
struct Sample {
  Eigen::Matrix<double, 7, 1> q;
  Eigen::Matrix4d T;
  Eigen::Matrix<double, 3, 7> link_pos;
};

std::vector<Sample> loadFixture(const std::string& path) {
  std::ifstream in(path);
  EXPECT_TRUE(in.good()) << "cannot open fixture " << path;
  std::vector<Sample> out;
  std::string line;
  while (std::getline(in, line)) {
    if (line.empty()) continue;
    std::stringstream ss(line);
    std::vector<double> v;
    std::string tok;
    while (std::getline(ss, tok, ',')) v.push_back(std::stod(tok));
    if (v.size() != 44) continue;
    Sample s;
    for (int i = 0; i < 7; ++i) s.q(i) = v[i];
    for (int r = 0; r < 4; ++r)
      for (int c = 0; c < 4; ++c) s.T(r, c) = v[7 + r * 4 + c];
    for (int i = 0; i < 7; ++i)
      for (int k = 0; k < 3; ++k) s.link_pos(k, i) = v[23 + i * 3 + k];
    out.push_back(s);
  }
  return out;
}
}  // namespace

TEST(FK, HomePoseMatchesConfig) {
  Robot robot = klib::load_robot_yaml(KINOVA_SCREWS_YAML);
  ForwardKinematics fk(robot);
  Eigen::VectorXd q = Eigen::VectorXd::Zero(robot.dof());
  EXPECT_TRUE(fk.body_pose(q).matrix().isApprox(robot.home_pose_M.matrix(), 1e-12));
}

TEST(FK, BodyPoseMatchesMujocoOnRandomConfigs) {
  Robot robot = klib::load_robot_yaml(KINOVA_SCREWS_YAML);
  ForwardKinematics fk(robot);
  auto samples = loadFixture(FK_REFERENCE_CSV);
  ASSERT_GE(samples.size(), 1000u);
  double max_err = 0.0;
  for (const auto& s : samples) {
    Eigen::Matrix4d T = fk.body_pose(s.q).matrix();
    max_err = std::max(max_err, (T - s.T).cwiseAbs().maxCoeff());
  }
  EXPECT_LT(max_err, 1e-9) << "max tool-pose error vs MuJoCo: " << max_err;
}

TEST(FK, LinkPosesMatchMujoco) {
  Robot robot = klib::load_robot_yaml(KINOVA_SCREWS_YAML);
  ForwardKinematics fk(robot);
  auto samples = loadFixture(FK_REFERENCE_CSV);
  double max_err = 0.0;
  for (const auto& s : samples) {
    auto poses = fk.link_poses(s.q);
    for (int i = 0; i < 7; ++i)
      max_err = std::max(max_err, (poses[i].translation() - s.link_pos.col(i)).cwiseAbs().maxCoeff());
  }
  EXPECT_LT(max_err, 1e-9) << "max link-position error vs MuJoCo: " << max_err;
}
