<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://relaxng.org/ns/structure/1.0"?>
<package format="3">
  <name>libkinematics</name>
  <version>0.1.0</version>
  <description>From-scratch SE(3)/SO(3) math, FK, Jacobians, IK, RNE dynamics, null-space utils.</description>
  <maintainer email="info@prandtldynamics.com">Derek Wang</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>eigen</depend>
  <depend>yaml-cpp</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
